services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  db:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:
  static_volume:


networks:
  app_network:
    driver: bridge
