services:
  web:
    build: .
    container_name: web
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  db:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app_network
    restart: always
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - web
    restart: "always"
    networks:
      - app_network
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  app_network:
    driver: bridge
